version: '3'

services:
  mysql:
    image: 'mariadb:latest'
    container_name: mysql
    networks:
      - shurly_app
    restart: always
    volumes:
      - ~/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=shurly_app
      - MYSQL_PASSWORD=shurly_app
      - MYSQL_DATABASE=shurly_app

  adminer:
    image: adminer
    container_name: adminer
    depends_on:
      - mysql
    networks:
      - shurly_app
    restart: always

  shurly_api:
    image: 'docker.pkg.github.com/invotyx/shurly_app/api_shurly_app:latest'
    container_name: shurly_api
    depends_on:
      - mysql
    networks:
      - shurly_app
    restart: always
    volumes:
      - ~/uploads/advertisement:/usr/src/app/uploads/advertisement
    environment:
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_HOST=mysql
      - TYPEORM_USERNAME=shurly_app
      - TYPEORM_PASSWORD=shurly_app
      - TYPEORM_DATABASE=shurly_app
      - TYPEORM_PORT=3306
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_MIGRATIONS_RUN=true
      - TYPEORM_LOGGING=false
      - TYPEORM_ENTITIES=build/entity/**/*.js
      - TYPEORM_MIGRATIONS=build/migration/**/*.js
      - PORT=3000

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - shurly_api
    networks:
      - shurly_app
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/uploads/advertisement:/var/www/html/uploads/advertisement
    ports:
      - '80:80'
      - '443:443'

networks:
  shurly_app:
    driver: bridge
