version: "3.7"

services:
  mysql:
    image: mariadb:10.5.8
    container_name: mysql
    networks:
      - shurly_app
    restart: always
    volumes:
      - ~/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=shurly_app
      - MYSQL_PASSWORD=shurly_app
      - MYSQL_DATABASE=shurly_app

  adminer:
    image: adminer:4.7.7
    container_name: adminer
    depends_on:
      - mysql
    networks:
      - shurly_app
    restart: always

  shurly_api:
    image: docker.pkg.github.com/invotyx/shurly_app/api_shurly_app:v1.0.0
    container_name: shurly_api
    depends_on:
      - mysql
    networks:
      - shurly_app
    restart: always
    volumes:
      - ~/uploads/advertisement:/usr/src/app/uploads/advertisement
    environment:
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_HOST=mysql
      - TYPEORM_USERNAME=shurly_app
      - TYPEORM_PASSWORD=shurly_app
      - TYPEORM_DATABASE=shurly_app
      - TYPEORM_PORT=3306
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_MIGRATIONS_RUN=true
      - TYPEORM_LOGGING=false
      - TYPEORM_ENTITIES=build/entity/**/*.js
      - TYPEORM_MIGRATIONS=build/migration/**/*.js
      - PORT=3000

  nginx:
    image: nginx:1.19.4
    container_name: nginx
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - shurly_api
    networks:
      - shurly_app
    restart: always
    volumes:
      - public_html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ~/uploads/advertisement:/var/www/html/uploads/advertisement
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - public_html:/usr/share/nginx/html
    depends_on:
      - nginx
    networks:
      - shurly_app

networks:
  shurly_app:
    name: shurly_app
    driver: bridge
