name: Publish Versioned Docker image
on:
  release:

jobs:
  push_api_to_github_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push backend to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: invotyx/shurly_app/api_shurly_app
          tag_with_ref: true
          path: .
